### PR TITLE
Added DLC Wheels Mod + Motorcycle Back Wheels (up-to-date GameBuild 2944) 

### PR DESCRIPTION
**Pull request by Manta95**

### CODE REVIEW

**Comment by Gellipapa** [comment]
@Manta95 Hi! Did you test that it works?

**Comment by Manta95** [comment]
> @Manta95 Hi! Did you test that it works?

Since 2019 it works yes. Only added updated wheels from time to time

**Comment by Manta95** [comment]
Different Bike's wheels front-rear
image
image
Race Wheels for example
image

**Comment by Manta95** [comment]
> Will it be a problem if my GameBuild is older? So I'm thinking here of those who haven't updated their gamebuild, don't have it not start because it's not up to date.

Surely yes... Have to put an option with config then

**Comment by Gellipapa** [comment]
> > Will it be a problem if my GameBuild is older? So I'm thinking here of those who haven't updated their gamebuild, don't have it not start because it's not up to date.
> 
> Surely yes... Have to put an option with config then

Yes we need config, but you need a config that checks what the current gamebuild is and if it's smaller it will automatically turn it off. So it's not necessarily up to the developer to turn it on/off. I think you can get the current game build in FiveM.

**Comment by Gellipapa** [comment]
https://docs.fivem.net/natives/?_0x804B9F7B This native get current game build.

**Comment by Manta95** [comment]
Thanks I knew it

**Comment by Manta95** [comment]
> > > Will it be a problem if my GameBuild is older? So I'm thinking here of those who haven't updated their gamebuild, don't have it not start because it's not up to date.
> > 
> > 
> > Surely yes... Have to put an option with config then
> 
> Yes we need config, but you need a config that checks what the current gamebuild is and if it's smaller it will automatically turn it off. So it's not necessarily up to the developer to turn it on/off. I think you can get the current game build in FiveM.

Without any changes, just turned of gamebuild (so i'm onto the original 1604) if I select addtional wheels categories, it just shows "by default" for 3 categories (race/dragster/street). But at least, you still use "bennys/bennysv2/motorcycles" wheels

image

**Comment by Manta95** [comment]
benny's wheels on a Blista, gamebuild 1602, without game break
image

**Comment by Gellipapa** [comment]
> > > > Will it be a problem if my GameBuild is older? So I'm thinking here of those who haven't updated their gamebuild, don't have it not start because it's not up to date.
> > > 
> > > 
> > > Surely yes... Have to put an option with config then
> > 
> > 
> > Yes we need config, but you need a config that checks what the current gamebuild is and if it's smaller it will automatically turn it off. So it's not necessarily up to the developer to turn it on/off. I think you can get the current game build in FiveM.
> 
> Without any changes, just turned of gamebuild (so i'm onto the original 1604) if I select addtional wheels categories, it just shows "by default" for 3 categories (race/dragster/street). But at least, you still use "bennys/bennysv2/motorcycles back wheels" wheels that weren't originaly in esx_lscustom
> 
> image

So you're saying it works fine with older gamebuilds?

**Comment by Manta95** [comment]
> 
> So you're saying it works fine with older gamebuilds?

That's right

**Comment by Gellipapa** [comment]
Okey, I believe you and merged.

**Pull request merged**
