### PR TITLE
Create tr.lua

### PR DESCRIPTION
**Pull request by Gold14567**

### CODE REVIEW

**Comment by Gellipapa** [comment]
@Gold14567 Hi! Thanks for the translation but we cannot accept it at the moment because it is incomplete. 

image

image

image

If you fix these, we can accept the PR. Thank you.

**Comment by Gold14567** [comment]
I will look into it tomorrow thanks for the notice

**Comment by Gold14567** [comment]
sorry for taking too long but i got it done

**Comment by Gellipapa** [comment]
@Gold14567 Hi! Thank you for your work, i merged.

**Pull request merged**
